### ISSUE TITLE
Pasting and Cutting doesn't work. 

### ISSUE THREAD

**Issue by jtree5757** [maxhetfeld/styler#13]
You have to press another key after you paste or cut for changes to take effect.

**Comment by sparcut** [comment]
+1, have tryed quite a few things but still unable to "save" copy and pasted CSS! Very annoying!

**Comment by jtree5757** [comment]
@sparcut I'm using this one currently [https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld](https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld)

It works, but you have to reload everytime for changes to take effect. A little annoying when developing, but it works.

**Comment by sparcut** [comment]
@jtree5757 Cheers, I'll try it out. Looks promising.

**Comment by maxhetfeld** [comment]
wontfix.

fake issue.
