### ISSUE TITLE
Export and Import

### ISSUE THREAD

**Issue by lbischof** [maxhetfeld/styler#17]
It would be great to have an export feature, so that I can backup my scripts. Something like a zip with a directory tree based on the URLs and a script.js and style.css in each directory?

**Comment by maxhetfeld** [comment]
It is backed up in Chrome Storage on your Google Account. You can use plugin to extract it:

https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en
